function Fx_sym = Fx_function(dt1,quat_sym1,quat_sym2,quat_sym3,quat_sym4,unbiased_accelerometer1,unbiased_accelerometer2,unbiased_accelerometer3)
%FX_FUNCTION
%    FX_SYM = FX_FUNCTION(DT1,QUAT_SYM1,QUAT_SYM2,QUAT_SYM3,QUAT_SYM4,UNBIASED_ACCELEROMETER1,UNBIASED_ACCELEROMETER2,UNBIASED_ACCELEROMETER3)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    07-Jul-2020 21:48:22

t2 = quat_sym1.^2;
t3 = quat_sym2.^2;
t4 = quat_sym3.^2;
t5 = quat_sym4.^2;
t6 = quat_sym1.*quat_sym2.*2.0;
t7 = quat_sym3.*quat_sym4.*2.0;
t8 = quat_sym1.*quat_sym4.*2.0;
t9 = quat_sym2.*quat_sym3.*2.0;
t10 = quat_sym1.*quat_sym3.*2.0;
t11 = t2-t3-t4+t5;
t12 = t11.*unbiased_accelerometer3;
t13 = quat_sym2.*quat_sym4.*2.0;
t14 = t6+t7;
t15 = t14.*unbiased_accelerometer2;
t16 = t2+t3-t4-t5;
t17 = t8-t9;
t18 = t10+t13;
t19 = t8+t9;
t20 = t2-t3+t4-t5;
t21 = t6-t7;
t22 = t20.*unbiased_accelerometer2;
t23 = t19.*unbiased_accelerometer1;
t24 = t22+t23-t21.*unbiased_accelerometer3;
t25 = t16.*unbiased_accelerometer1;
t26 = t18.*unbiased_accelerometer3;
t27 = t25+t26-t17.*unbiased_accelerometer2;
t28 = dt1.*t27;
t29 = t10-t13;
t30 = dt1.*t17;
t31 = dt1.*t21;
t32 = dt1.*t29;
Fx_sym = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,dt1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,dt1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,dt1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-dt1.*(t12+t15-t29.*unbiased_accelerometer1),dt1.*t24,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,dt1.*(t12+t15-unbiased_accelerometer1.*(t10-quat_sym2.*quat_sym4.*2.0)),0.0,-t28,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-dt1.*t24,t28,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-dt1.*t16,-dt1.*t19,t32,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t30,-dt1.*t20,-dt1.*t14,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-dt1.*t18,t31,-dt1.*t11,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-dt1.*t16,-dt1.*t19,t32,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t30,-dt1.*t20,-dt1.*t14,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-dt1.*t18,t31,-dt1.*t11,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0],[18,18]);
