%% Search for a specified operating point for the model - sixdofTrim.
%
% This MATLAB script is the command line equivalent of the trim model
% tab in linear analysis tool with current specifications and options.
% It produces the exact same operating points as hitting the Trim button.

% MATLAB(R) file generated by MATLAB(R) 9.6 and Simulink Control Design (TM) 5.3.
%
% Generated on: 29-Dec-2019 13:33:15

%% Specify the model name
model = 'sixdofTrim';

%% Create the operating point specification object.
opspec = operspec(model);

%% Set the constraints on the states in the model.
% - The defaults for all states are Known = false, SteadyState = true,
%   Min = -Inf, Max = Inf, dxMin = -Inf, and dxMax = Inf.

% State (1) - sixdofTrim/Rocket Dynamics/6DOF (Quaternion)/Calculate DCM & Euler Angles/q0 q1 q2 q3
% - Default model initial conditions are used to initialize optimization.
opspec.States(1).Known = [true;true;true;true];

% State (2) - sixdofTrim/Rocket Dynamics/6DOF (Quaternion)/p,q,r
% - Default model initial conditions are used to initialize optimization.
opspec.States(2).Known = [false;true;true];
opspec.States(2).SteadyState = [false;true;true];

% State (3) - sixdofTrim/Rocket Dynamics/6DOF (Quaternion)/ub,vb,wb
% - Default model initial conditions are used to initialize optimization.
opspec.States(3).Known = [true;true;false];
opspec.States(3).SteadyState = [true;true;false];

% State (4) - sixdofTrim/Rocket Dynamics/6DOF (Quaternion)/xe,ye,ze
% - Default model initial conditions are used to initialize optimization.
opspec.States(4).SteadyState = [false;false;false];
opspec.States(4).Min = [-Inf;-Inf;1];

% State (5) - sixdofTrim/Rocket Dynamics/Calculate Forces and Moments/All conditions/Subsystem/Discrete Wind Gust Model/Distance into gust (x)/Distance into Gust (x) (Limited to gust length d)
% - Default model initial conditions are used to initialize optimization.
opspec.States(5).SteadyState = false;

% State (6) - sixdofTrim/Rocket Dynamics/Calculate Forces and Moments/All conditions/Subsystem/Discrete Wind Gust Model/Distance into gust (y)/Distance into Gust (x) (Limited to gust length d)
% - Default model initial conditions are used to initialize optimization.
opspec.States(6).SteadyState = false;

% State (7) - sixdofTrim/Rocket Dynamics/Calculate Forces and Moments/All conditions/Subsystem/Discrete Wind Gust Model/Distance into gust (z)/Distance into Gust (x) (Limited to gust length d)
% - Default model initial conditions are used to initialize optimization.
opspec.States(7).SteadyState = false;

% State (8) - sixdofTrim/Rocket Dynamics/Calculate Forces and Moments/All conditions/Subsystem/Von Karman Wind Turbulence Model  (Continuous (+q +r))/Filters on angular rates/Hpgw/Unit Delay
% - Default model initial conditions are used to initialize optimization.
opspec.States(8).SteadyState = [false;false];

% State (9) - sixdofTrim/Rocket Dynamics/Calculate Forces and Moments/All conditions/Subsystem/Von Karman Wind Turbulence Model  (Continuous (+q +r))/Filters on angular rates/Hqgw/Unit Delay
% - Default model initial conditions are used to initialize optimization.
opspec.States(9).SteadyState = [false;false];

% State (10) - sixdofTrim/Rocket Dynamics/Calculate Forces and Moments/All conditions/Subsystem/Von Karman Wind Turbulence Model  (Continuous (+q +r))/Filters on angular rates/Hqgw/Unit Delay1
% - Default model initial conditions are used to initialize optimization.
opspec.States(10).SteadyState = [false;false];

% State (11) - sixdofTrim/Rocket Dynamics/Calculate Forces and Moments/All conditions/Subsystem/Von Karman Wind Turbulence Model  (Continuous (+q +r))/Filters on angular rates/Hrgw/Unit Delay
% - Default model initial conditions are used to initialize optimization.
opspec.States(11).SteadyState = [false;false];

% State (12) - sixdofTrim/Rocket Dynamics/Calculate Forces and Moments/All conditions/Subsystem/Von Karman Wind Turbulence Model  (Continuous (+q +r))/Filters on angular rates/Hrgw/Unit Delay1
% - Default model initial conditions are used to initialize optimization.
opspec.States(12).SteadyState = [false;false];

% State (13) - sixdofTrim/Rocket Dynamics/Calculate Forces and Moments/All conditions/Subsystem/Von Karman Wind Turbulence Model  (Continuous (+q +r))/Filters on velocities/Hugw(z)/Unit Delay
% - Default model initial conditions are used to initialize optimization.
opspec.States(13).SteadyState = [false;false];

% State (14) - sixdofTrim/Rocket Dynamics/Calculate Forces and Moments/All conditions/Subsystem/Von Karman Wind Turbulence Model  (Continuous (+q +r))/Filters on velocities/Hvgw(z)/Unit Delay
% - Default model initial conditions are used to initialize optimization.
opspec.States(14).SteadyState = [false;false];

% State (15) - sixdofTrim/Rocket Dynamics/Calculate Forces and Moments/All conditions/Subsystem/Von Karman Wind Turbulence Model  (Continuous (+q +r))/Filters on velocities/Hwgw(z)/Unit Delay
% - Default model initial conditions are used to initialize optimization.
opspec.States(15).SteadyState = [false;false];

%% Set the constraints on the inputs in the model.
% - The defaults for all inputs are Known = false, Min = -Inf, and
% Max = Inf.

% Input (1) - sixdofTrim/Euler Angle Gimbal X
% - Default model initial conditions are used to initialize optimization.
opspec.Inputs(1).Min = -0.061087;
opspec.Inputs(1).Max = 0.061087;

% Input (2) - sixdofTrim/Euler Angle Gimbal Y
% - Default model initial conditions are used to initialize optimization.
opspec.Inputs(2).Min = -0.061087;
opspec.Inputs(2).Max = 0.061087;

%% Set the constraints on the outputs in the model.
% - The defaults for all outputs are Known = false, Min = -Inf, and
% Max = Inf.

% Output (1) - sixdofTrim/Error Quaternion
% - Default model initial conditions are used to initialize optimization.


%% Create the options
opt = findopOptions('DisplayReport','iter');
opt.OptimizationOptions.MaxFunEvals = 20000;
opt.OptimizationOptions.MaxIter = 40000;

%% Perform the operating point search.
[op,opreport] = findop(model,opspec,opt);
